config/routes.rb
Rails.application.routes.draw do
  
  devise_for :models
  # get 'users/index'
  root 'users#index'
  # get 'users/:id/edit'
  #  get 'user', to:'users#show' 
  # patch '/users/:id'
  # delete '/users/:id'
  resources :users do
    resources :books
  end
   
  # resource: user
  # resolve('users') {[:user]}
  # resolve('Geocoder') { [:geocoder] }
  # resources:users
  # resources:users, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user

   
  validates :book, presence: true
  validates :catagory, presence: true
end

app/models/concerns/visible.rb
module Visible
    def archived?
        status == 'archived'
    end
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
# database_authenticable:- User can authenticate themselve set login password password. Password will be stored in database.
# registrable:- User can register themselves and can edit or delete their account.
# recoverible: user can reset their password and recover their account if they forget their credentials
# rememberable:- This module remembers a user’s sessions by saving the information in a browser cookie.
# validatable: This module provides validations for the user’s email and password fields. (For example, your application asks for the password to be at least six characters, even though you haven’t defined any custom validations in your model.)

app/models/user.rb
class User < ApplicationRecord
    # before_action:authenticate_user!
    def how_old_itis
        # "I'm"+" "+self.age.to_s+" years old"
        "I'm #{self.age.to_s} old"
    end
    validates :name, presence: true
    validates :age, presence: true, length: {maximum: 2}
    validates :phone_no, presence: true, length: {minimum:10}
    validates :email, presence:true  
    

    has_many :books

    has_one_attached :image 

    # VALID_STATUS = ['public', 'private', 'archived']
    
    # validates :status, inclusion: { in: VALID_STATUS }
     
    # def archived?
    #     status == 'archived'
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action:authenticate_model!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # http_basic_authenticate_with name:"dhh", password:"secret", only: :destroy
    def create
        @user=User.find(params[:user_id])
        @book=@user.books.create(book_params)
        # if @book.save
        #   redirect_to root_path
        # else
        
       redirect_to users_path(@user)

    end
   def edit
     @user=User.find(params[:user_id])
     @book=@user.books.find(params[:id])
   end
   
    def update
      @user = User.find(params[:id])   
      @ebd=@user.books.update(book_params)
      # if @user.update(user_params)   

      #   redirect_to root_path
    end
    private
      def book_params
        params.require(:book).permit(:book, :catagory)
      end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # http_basic_authenticate_with name:"dhh", password:"secret", except: [:index, :show]
  def index
    @users=User.all 
    # special variable
  end

  def show
    @user =User.find(params[:id])  
    # any name can use as variable name  
  end

  def new
    @user=User.new
  end

  def edit
    @user = User.find(params[:id])   
  end

  def create
    @user = User.new(user_params)  
    if @user.save!    
      redirect_to root_path 
      # or you can use your model name for redirection @user  
    else     
      render :new   
    end   
  end

  def update
    @user = User.find(params[:id])   
    if @user.update(user_params)   
      # flash[:notice] = 'User updated!'   
      # redirect_to @user
      redirect_to root_path
    else   
      # flash[:error] = 'Failed to edit User!'   
      render :edit  
    end   
  end


  def destroy
    @user = User.find(params[:id])   
      @user.destroy   
      # redirect_to root_path  
      redirect_to root_path 
      # it's predefine that after destroy redirect to page on root

  end

  private
  def user_params   
    params.require(:user).permit(:name, :age, :email, :phone_no, :image)   
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<% det.each do |page| %>
<p>
    <strong>Book:</strong>
    <%= page.book%>
</p>
<p>
    <strong>Catagory:</strong>
    <%= page.catagory%>
</p>    
<% end %>    

app/views/books/_form.html.erb
<%= form_with model: [ @user, @user.books.build ] do |form| %>
<p>
    <%= form.label :Book%>
    <%= form.text_field :book%>
</p>
<p>
    <%= form.label :Catagory%>
    <%= form.text_area :catagory%>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

app/views/books/_form1.html.erb
<%= form_with model: nb do |page| %>
  <div>
    <%= page.label :Book %><br>
    <%= page.text_field :book %>
  </div>

  <div>
    <%= page.label :Catagory %><br>
    <%= page.text_area :catagory %><br>

  <div>
    <%= page.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<%= render "form1", nb: @book %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thirdproj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |page| %>
  <div>
    <%= page.label :Name %><br>
    <%= page.text_field :name %>
  </div>

  <div>
    <%= page.label :Age %><br>
    <%= page.number_field :age %><br>
  </div>

  <div>
    <%= page.label :Email %><br>
    <%= page.text_field :email %><br>
  </div>
  <div>
    <%= page.label :Phone_No %><br>
    <%= page.number_field :phone_no %><br>

  </div>

   <br>
   <div>
    <%= page.label :choose_image_and_upload %><br>
    <br>
    <%= page.file_field :image%><br>
    <br>
  <div>
    <%= page.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Details</h1>

<%= render "form", user: @user %>
<%# <%= link_to "You want to show updated details click it", index_user_path%>

app/views/users/index.html.erb
<h1>Users</h1>

<% if model_signed_in? %>

<%# this helper method associated with device's controller. It checks whether the user is signed in or not and returns a boolean true or false value%>

  <p>Hello! Users <%= current_model.email %></p>
  <%= button_to "sign out", destroy_model_session_path, method: :delete%>
   
  <%# current_user is a Devise helper that accesses the details of the user who is currently signed in to the application. For instance, if you sign in with sammy@example.com, the current_user helper would return the user model for sammy@example.com. So, when using current_user.email, you would get sammy@example.com as the result. By using Devise, you avoid having to implement this logic from scratch, saving you time and effort. %>
  



<% else %>
  <% link_to "Sign_in", new_user_session_path %>
<% end %>  


<%# You are using the button_to method to define a button that takes the user to a specific route. You are also using helper methods to get these routes: destroy_user_session_path resolves to /users/sign_out and new_user_session_path resolves to /users/sign_in. (You can review the full list of route URL helpers by running bundle exec rails routes as mentioned in a previous step.)

 %>



<h1>Existing User</h1>

<ul>
  <% @users.each do |article| %>
  <a href="/users/<%= article.id%>">
    <li>
      <%= article.name %>
    </li>
   <% end %>
</ul>

<%= link_to "Create New User", new_user_path%>


<%# <% @users.each do |article| %>
    <%# <li>
      <a href="/users/<%= article.id %>
        <%# <%= article.name%>
      <%# </a> 
    </li> %>
  <%# <% end %> 
<%# </ol> %>
<%# 
@users.each do |f| %>
<%# <p>Name: <%= f.name </p>%>
<%# <p>age: <%= f.age </p>%>
<%# <p>Email: <%= f.email </p>%>
<%# <p>Phone_no: <%= f.phone_no </p>%>
<%# <% end %>
<%# </ol> %>
<%
=begin %>
<h1>User Name and their details</h1>

<ul>
  <% @users.each do |article| %>
    <li>
      <a href="<%= user_path(article) %>">
        <%= article.name %>
      </a>
    </li>
  <% end %>
</ul>
<%
=end  %>
<%
=begin
%>
<h1>Articles</h1>

<ul>
  <% @users.each do |article| %>
    <li>
      <%= link_to article.name %>
    </li>
  <% end %>
</ul>
<%
=end
%> 

app/views/users/new.html.erb
<%
=begin %>
<h1>New Article</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age%><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%
=end %>

<%
=begin
%>
<h1>Enter user details</h1>

<%= form_with model: @user, url: users_path, method: :POST do |form| %>
  <div>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :Age %><br>
    <%= form.number_field :age %><br>
  </div>

   <div>
    <%= form.label :Phone_No %><br>
    <%= form.number_field :phone_no %><br>
  </div>

  <div>
    <%= form.label :Email %><br>
    <%= form.text_field :email %><br>
  <div>
    <%= form.submit %>
  </div>
  <% end %>
<%
=end
%>
  <h1>New User</h1>

 <%= render "form", user: @user %>


  

app/views/users/show.html.erb
<%# <%= model: @user, url: users_path, method: :POST do |form| %>


<h1>User Details</h1>

<p>Name: <%= @user.name%> 

Age: <%= @user.age%>

E-mail: <%= @user.email%>

Phone_no: <%= @user.phone_no%>
</p>

<ul>
    <li><%= link_to "Edit", edit_user_path(@user) 
    # this @user is id which is predefine rails 
    %></li>
    <li><%= link_to "Destroy", user_path(@user),data: {
    # this @user also called id whcih is predefine autometically called by rails
    turbo_method: :delete, 
    # this delete is http verb which define routes
    turbo_confirm: "Are you sure?"}
    %></li>
    <li><%= link_to "Home Page", users_path %></li> 
</ul>
<h2>"Add a book"</h2>
<%= render "books/form" %>


<h2>Books</h2>
<%= render "books/book",  det: @user.books %>

<%# <h2>Edit to add book</h2>
<%= link_to "Edit", edit_user_book_path(@user) %>